// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTCcSbOEct4tEydNXQUKuPqV8zKJ-OL2c',
    appId: '1:435481162851:web:b3f2b2e29d356f42ca7456',
    messagingSenderId: '435481162851',
    projectId: 'farm-ges',
    authDomain: 'farm-ges.firebaseapp.com',
    storageBucket: 'farm-ges.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGdRJMbHrhVfsCZ6eFVcMChXc1UeFZxXA',
    appId: '1:435481162851:android:8feadedf7aca6006ca7456',
    messagingSenderId: '435481162851',
    projectId: 'farm-ges',
    storageBucket: 'farm-ges.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAbcs6KpQIiAmb_hVkaVwbSy3TG5ZIbr8',
    appId: '1:435481162851:ios:2fd611142d28974cca7456',
    messagingSenderId: '435481162851',
    projectId: 'farm-ges',
    storageBucket: 'farm-ges.appspot.com',
    iosClientId: '435481162851-dkp9hvdvkbi6gcl0kd3a36nt1e75qu4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmges',
  );
}
